/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juliafractal;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.WritableRaster;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Guilherme
 */
public class Tela extends javax.swing.JFrame {

    private double real, imaginario;
    private double RANGE_REAL_INI, RANGE_REAL_FIM;
    private double RANGE_IMAG_INI, RANGE_IMAG_FIM;
    private int MAX_INTERATIONS;
    private double DIF_RANGE;
    private double FACTOR;
    private double zoom = 10;
    private int TIPO_EQ = 1;
    BufferedImage imagemOriginal;

    public Tela() {
        initComponents();
        reinicializaParametros();
        jLabelImagem.setCursor(new Cursor(Cursor.HAND_CURSOR));
        gerar();
    }

    public void reinicializaParametros() {

        RANGE_REAL_INI = -1.5;
        RANGE_REAL_FIM = 1.5;
        RANGE_IMAG_INI = -1.5;
        RANGE_IMAG_FIM = 1.5;
        DIF_RANGE = RANGE_REAL_FIM - RANGE_REAL_INI;
        FACTOR = (RANGE_REAL_FIM - RANGE_REAL_INI) / jLabelImagem.getWidth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEquacoes = new javax.swing.ButtonGroup();
        jLabelImagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldReal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldImaginario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldZoom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIteracoes = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonEq1 = new javax.swing.JRadioButton();
        jRadioButtonEq2 = new javax.swing.JRadioButton();
        jRadioButtonEq3 = new javax.swing.JRadioButton();
        jRadioButtonEq4 = new javax.swing.JRadioButton();
        jRadioButtonEq5 = new javax.swing.JRadioButton();
        jRadioButtonEq6 = new javax.swing.JRadioButton();
        jRadioButtonEq7 = new javax.swing.JRadioButton();
        jLabelXCoord = new javax.swing.JLabel();
        jLabelYCoord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelImagem.setToolTipText("Zoom In/Out");
        jLabelImagem.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelImagemMouseMoved(evt);
            }
        });
        jLabelImagem.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabelImagemMouseWheelMoved(evt);
            }
        });
        jLabelImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImagemMouseClicked(evt);
            }
        });

        jLabel1.setText("Real:");

        jTextFieldReal.setText("-0.67319");
        jTextFieldReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRealActionPerformed(evt);
            }
        });

        jLabel2.setText("Imaginário:");

        jTextFieldImaginario.setText("0.34442");
        jTextFieldImaginario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImaginarioActionPerformed(evt);
            }
        });

        jButton1.setText("Gerar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Zoom:");

        jTextFieldZoom.setText("10");

        jLabel4.setText("Iterações:");

        jTextFieldIteracoes.setText("128");
        jTextFieldIteracoes.setToolTipText("Zoom In/Out");

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSlider1.setValue(10);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel5.setText("Matiz:");

        jLabel6.setText("Saturação:");

        jSlider2.setValue(0);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        jLabel7.setText("Tipo de função:");

        buttonGroupEquacoes.add(jRadioButtonEq1);
        jRadioButtonEq1.setSelected(true);
        jRadioButtonEq1.setText("f(z) = z^2+c");
        jRadioButtonEq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEq1ActionPerformed(evt);
            }
        });

        buttonGroupEquacoes.add(jRadioButtonEq2);
        jRadioButtonEq2.setText("f(z) = z^3+c");
        jRadioButtonEq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEq2ActionPerformed(evt);
            }
        });

        buttonGroupEquacoes.add(jRadioButtonEq3);
        jRadioButtonEq3.setText("f(z) = (z^2+c) / (z-c)");

        buttonGroupEquacoes.add(jRadioButtonEq4);
        jRadioButtonEq4.setText("f(z) = z^2+z + c");

        buttonGroupEquacoes.add(jRadioButtonEq5);
        jRadioButtonEq5.setText("f(z) = exp(z) - c");

        buttonGroupEquacoes.add(jRadioButtonEq6);
        jRadioButtonEq6.setText("f(z) = [(z2+z)/Ln(z)] +c");

        buttonGroupEquacoes.add(jRadioButtonEq7);
        jRadioButtonEq7.setText("f(z) = exp(z)+c");

        jLabelXCoord.setText("X:");

        jLabelYCoord.setText("Y:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldReal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldImaginario, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldZoom)
                                    .addComponent(jTextFieldIteracoes, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jRadioButtonEq1)
                            .addComponent(jRadioButtonEq2)
                            .addComponent(jRadioButtonEq3)
                            .addComponent(jRadioButtonEq4)
                            .addComponent(jRadioButtonEq5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonEq7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton2)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jRadioButtonEq6)
                                    .addGap(25, 25, 25)))
                            .addComponent(jLabelXCoord)
                            .addComponent(jLabelYCoord)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldImaginario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonEq1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonEq2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonEq3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonEq4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonEq5)
                .addGap(2, 2, 2)
                .addComponent(jRadioButtonEq6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonEq7)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(50, 50, 50)
                .addComponent(jLabelXCoord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelYCoord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRealActionPerformed

    private void jTextFieldImaginarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImaginarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImaginarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gerar();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void gerar() {
        reinicializaParametros();
        real = Double.parseDouble(jTextFieldReal.getText());
        imaginario = Double.parseDouble(jTextFieldImaginario.getText());
        zoom = Double.parseDouble(jTextFieldZoom.getText());
        MAX_INTERATIONS = Integer.parseInt(jTextFieldIteracoes.getText());
        if (jRadioButtonEq1.isSelected()) {
            TIPO_EQ = 1;
        }
        if (jRadioButtonEq2.isSelected()) {
            TIPO_EQ = 2;
        }
        if (jRadioButtonEq3.isSelected()) {
            TIPO_EQ = 3;
        }
        if (jRadioButtonEq4.isSelected()) {
            TIPO_EQ = 4;
        }
        if (jRadioButtonEq5.isSelected()) {
            TIPO_EQ = 5;
        }
        if (jRadioButtonEq6.isSelected()) {
            TIPO_EQ = 6;
        }
        if (jRadioButtonEq7.isSelected()) {
            TIPO_EQ = 7;
        }
        JuliaFractal julia = new JuliaFractal(real, imaginario, RANGE_REAL_INI, RANGE_REAL_FIM, RANGE_IMAG_INI, RANGE_IMAG_FIM, FACTOR, MAX_INTERATIONS, TIPO_EQ, 0, 0);
        jLabelImagem.setIcon(new ImageIcon(julia.getImage()));
        imagemOriginal = julia.getImage();
    }
    private void jLabelImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImagemMouseClicked
        zoom = Double.parseDouble(jTextFieldZoom.getText());
        MAX_INTERATIONS = Integer.parseInt(jTextFieldIteracoes.getText());
        if (SwingUtilities.isLeftMouseButton(evt)) {
            //System.out.println(evt.getX() + "," + evt.getY());
            double xClick = evt.getX();
            double yClick = jLabelImagem.getHeight() - evt.getY();
            double x = ((xClick / jLabelImagem.getWidth()) * (RANGE_REAL_FIM - RANGE_REAL_INI)) + RANGE_REAL_INI;
            double y = ((yClick / jLabelImagem.getHeight()) * (RANGE_IMAG_FIM - RANGE_IMAG_INI)) + RANGE_IMAG_INI;
            //System.out.println("Clicou em " + x + "," + y);
            FACTOR = FACTOR / zoom;
            DIF_RANGE = DIF_RANGE / zoom;
            RANGE_REAL_INI = x - (DIF_RANGE / 2);
            RANGE_REAL_FIM = x + (DIF_RANGE / 2);
            RANGE_IMAG_INI = y - (DIF_RANGE / 2);
            RANGE_IMAG_FIM = y + (DIF_RANGE / 2);
            //System.out.println("Começara em " + RANGE_REAL_INI + "," + RANGE_REAL_FIM);
            JuliaFractal julia = new JuliaFractal(real, imaginario, RANGE_REAL_INI, RANGE_REAL_FIM, RANGE_IMAG_INI, RANGE_IMAG_FIM, FACTOR, MAX_INTERATIONS, TIPO_EQ, 0, 0);
            jLabelImagem.setIcon(new ImageIcon(julia.getImage()));
            imagemOriginal = julia.getImage();
        } else {
            //System.out.println(evt.getX() + "," + evt.getY());
            double xClick = evt.getX();
            double yClick = 500 - evt.getY();
            double x = ((xClick / 500) * (RANGE_REAL_FIM - RANGE_REAL_INI)) + RANGE_REAL_INI;
            double y = ((yClick / 500) * (RANGE_IMAG_FIM - RANGE_IMAG_INI)) + RANGE_IMAG_INI;
            //System.out.println("Clicou em " + x + "," + y);
            FACTOR = FACTOR * zoom;
            DIF_RANGE = DIF_RANGE * zoom;
            RANGE_REAL_INI = x - (DIF_RANGE / 2);
            RANGE_REAL_FIM = x + (DIF_RANGE / 2);
            RANGE_IMAG_INI = y - (DIF_RANGE / 2);
            RANGE_IMAG_FIM = y + (DIF_RANGE / 2);
            //System.out.println("Começara em " + RANGE_REAL_INI + "," + RANGE_REAL_FIM);
            JuliaFractal julia = new JuliaFractal(real, imaginario, RANGE_REAL_INI, RANGE_REAL_FIM, RANGE_IMAG_INI, RANGE_IMAG_FIM, FACTOR, MAX_INTERATIONS, TIPO_EQ, 0, 0);
            jLabelImagem.setIcon(new ImageIcon(julia.getImage()));
            imagemOriginal = julia.getImage();
        }
        System.out.println("FACTOR:" + FACTOR);
        System.out.println("DIF_RANGE:" + DIF_RANGE);
    }//GEN-LAST:event_jLabelImagemMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextFieldReal.setText(real + "");
        jTextFieldImaginario.setText(imaginario + "");
        MAX_INTERATIONS = Integer.parseInt(jTextFieldIteracoes.getText());
        JuliaFractal julia = new JuliaFractal(real, imaginario, RANGE_REAL_INI, RANGE_REAL_FIM, RANGE_IMAG_INI, RANGE_IMAG_FIM, FACTOR, MAX_INTERATIONS, TIPO_EQ, 0, 0);
        jLabelImagem.setIcon(new ImageIcon(julia.getImage()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabelImagemMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabelImagemMouseWheelMoved
        int rotacoes = evt.getWheelRotation();
        zoom = 1.2;
        MAX_INTERATIONS = Integer.parseInt(jTextFieldIteracoes.getText());
        if (rotacoes < 0) {
            System.out.println(evt.getX() + "," + evt.getY());
            double xClick = evt.getX();
            double yClick = jLabelImagem.getHeight() - evt.getY();
            double x = ((xClick / jLabelImagem.getWidth()) * (RANGE_REAL_FIM - RANGE_REAL_INI)) + RANGE_REAL_INI;
            double y = ((yClick / jLabelImagem.getHeight()) * (RANGE_IMAG_FIM - RANGE_IMAG_INI)) + RANGE_IMAG_INI;
            FACTOR = FACTOR / zoom;
            DIF_RANGE = DIF_RANGE / zoom;
            RANGE_REAL_INI = x - (DIF_RANGE / 2);
            RANGE_REAL_FIM = x + (DIF_RANGE / 2);
            RANGE_IMAG_INI = y - (DIF_RANGE / 2);
            RANGE_IMAG_FIM = y + (DIF_RANGE / 2);
            JuliaFractal julia = new JuliaFractal(real, imaginario, RANGE_REAL_INI, RANGE_REAL_FIM, RANGE_IMAG_INI, RANGE_IMAG_FIM, FACTOR, MAX_INTERATIONS, TIPO_EQ, 0, 0);
            jLabelImagem.setIcon(new ImageIcon(julia.getImage()));
        } else {
            double xClick = evt.getX();
            double yClick = 500 - evt.getY();
            double x = ((xClick / 500) * (RANGE_REAL_FIM - RANGE_REAL_INI)) + RANGE_REAL_INI;
            double y = ((yClick / 500) * (RANGE_IMAG_FIM - RANGE_IMAG_INI)) + RANGE_IMAG_INI;
            FACTOR = FACTOR * zoom;
            DIF_RANGE = DIF_RANGE * zoom;
            RANGE_REAL_INI = x - (DIF_RANGE / 2);
            RANGE_REAL_FIM = x + (DIF_RANGE / 2);
            RANGE_IMAG_INI = y - (DIF_RANGE / 2);
            RANGE_IMAG_FIM = y + (DIF_RANGE / 2);
            JuliaFractal julia = new JuliaFractal(real, imaginario, RANGE_REAL_INI, RANGE_REAL_FIM, RANGE_IMAG_INI, RANGE_IMAG_FIM, FACTOR, MAX_INTERATIONS, TIPO_EQ, 0, 0);
            jLabelImagem.setIcon(new ImageIcon(julia.getImage()));
        }
    }//GEN-LAST:event_jLabelImagemMouseWheelMoved
    public static BufferedImage copyImage(BufferedImage source) {
        BufferedImage b = new BufferedImage(source.getWidth(), source.getHeight(), source.getType());
        Graphics g = b.getGraphics();
        g.drawImage(source, 0, 0, null);
        g.dispose();
        return b;
    }
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        BufferedImage image = copyImage(imagemOriginal);
        for (int i = 0; i < image.getWidth(); i++) {
            for (int j = 0; j < image.getHeight(); j++) {
                float hsv[] = new float[3];
                Color cor = new Color(image.getRGB(i, j));
                cor.RGBtoHSB(cor.getRed(), cor.getGreen(), cor.getBlue(), hsv);
                float sliderHValue = jSlider1.getValue();
                float sliderSValue = jSlider2.getValue();
                sliderHValue /= 100;
                sliderSValue /= 100;
                hsv[0] = hsv[0] + sliderHValue;
                hsv[1] = hsv[1] - sliderSValue;
                int corrgb = Color.HSBtoRGB(hsv[0], hsv[1], hsv[2]);
                image.setRGB(i, j, corrgb);
            }
        }
        jLabelImagem.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        BufferedImage image = copyImage(imagemOriginal);
        for (int i = 0; i < image.getWidth(); i++) {
            for (int j = 0; j < image.getHeight(); j++) {
                float hsv[] = new float[3];
                Color cor = new Color(image.getRGB(i, j));
                cor.RGBtoHSB(cor.getRed(), cor.getGreen(), cor.getBlue(), hsv);
                float sliderHValue = jSlider1.getValue();
                float sliderSValue = jSlider2.getValue();
                sliderHValue /= 100;
                sliderSValue /= 100;
                hsv[0] = hsv[0] + sliderHValue;
                hsv[1] = hsv[1] - sliderSValue;
                int corrgb = Color.HSBtoRGB(hsv[0], hsv[1], hsv[2]);
                image.setRGB(i, j, corrgb);
            }
        }
        jLabelImagem.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_jSlider2StateChanged

    private void jRadioButtonEq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEq1ActionPerformed

    private void jRadioButtonEq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEq2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEq2ActionPerformed

    private void jLabelImagemMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImagemMouseMoved

        double xClick = evt.getX();
        double yClick = jLabelImagem.getHeight() - evt.getY();
        double x = ((xClick / jLabelImagem.getWidth()) * (RANGE_REAL_FIM - RANGE_REAL_INI)) + RANGE_REAL_INI;
        double y = ((yClick / jLabelImagem.getHeight()) * (RANGE_IMAG_FIM - RANGE_IMAG_INI)) + RANGE_IMAG_INI;
        jLabelXCoord.setText("X:" + x);
        jLabelYCoord.setText("Y:" + y);
    }//GEN-LAST:event_jLabelImagemMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupEquacoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelXCoord;
    private javax.swing.JLabel jLabelYCoord;
    private javax.swing.JRadioButton jRadioButtonEq1;
    private javax.swing.JRadioButton jRadioButtonEq2;
    private javax.swing.JRadioButton jRadioButtonEq3;
    private javax.swing.JRadioButton jRadioButtonEq4;
    private javax.swing.JRadioButton jRadioButtonEq5;
    private javax.swing.JRadioButton jRadioButtonEq6;
    private javax.swing.JRadioButton jRadioButtonEq7;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTextField jTextFieldImaginario;
    private javax.swing.JTextField jTextFieldIteracoes;
    private javax.swing.JTextField jTextFieldReal;
    private javax.swing.JTextField jTextFieldZoom;
    // End of variables declaration//GEN-END:variables
}
